### ISSUE TITLE
Error while running with download-resources

### ISSUE THREAD

**Issue by krutkinam** [iquasere/reCOGnizer#2]
Hi!

I am using reCOGnizer (version 1.4.3) from Conda on Debian 10. 

This is how I launch the program:
`recognizer.py -f input_file.fasta -o recognizer_output --download-resources`

So, I hope, that all the resources were downloaded correctly (63 383 files). But I'm getting these errors:
```
~/Programs/anaconda3/share/resources_directory/cd_10_0.aux not found!
Some part of CDD was not valid!
Generating databases for [10] threads.
...
ERROR: line 3797: "wordScoreThreshold": unexpected member, should be one of: "scores" "lambda" "kappa" "h" "scalingFactor" "lambdaUngapped" "kappaUngapped" "hUngapped" 
...
~/Programs/anaconda3/share/resources_directory/pfam_10_0.aux not found!
Some part of Pfam was not valid!
...
~/Programs/anaconda3/share/resources_directory/NF_10_0.aux not found!
Some part of NCBIfam was not valid!
...
BLAST engine error: Cannot retrieve path to RPS database
...
2021-03-19 10:07:06: Organizing annotation results
[1/8] Handling CDD identifications
Traceback (most recent call last):
  File "~/Programs/anaconda3/bin/recognizer.py", line 477, in <module>
    main()
  File "~/Programs/anaconda3/bin/recognizer.py", line 413, in main
    report = parse_blast('{}/{}_aligned.blast'.format(args.output, db))
  File "~/Programs/anaconda3/bin/recognizer.py", line 205, in parse_blast
    blast = pd.read_csv(file, sep='\t', header=None)
  File "~/Programs/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "~/Programs/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "~/Programs/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "~/Programs/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "~/Programs/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

Could you help me with this, please?

Thanks!

**Comment by iquasere** [comment]
I had not yet encountered this error! Running ```conda install -c bioconda -y blast=2.10.1``` should fix it! 

Seems like blast was recently updated, and the new version has some different rules to its use. Very weird that TIGRFAM and KOG databases could still be built, but not the others...

**Comment by krutkinam** [comment]
Thank you so much for the quick response!

My `blast`'s version was 2.5.0 and I had a lot of conflicts when I tried to update it to 2.10.1. So, I created conda env for reCOGnizer, but faced another error at the end of the installation process:

`ModuleNotFoundError: No module named 'xlsxwriter'`

I have installed it using `pip` and it worked!

**Comment by iquasere** [comment]
As future advice, install with [mamba](https://anaconda.org/conda-forge/mamba). It can solve everything that makes sense.

About xlsxwriter, I see it was not specified in the [yaml](https://github.com/iquasere/reCOGnizer/blob/master/meta.yaml), thank you for pointing it out!
