### ISSUE TITLE
problem with resouces download and rebuilding the databases

### ISSUE THREAD

**Issue by gaworj** [iquasere/reCOGnizer#5]
Hi,

I have recently updated recognizer to the newest version using conda and such error appears after running the tool:

recognizer.py -t 12 -f IBB3394_genome_dfast_out/protein.faa -o IBB3394_protein_recognizer_COG_out -rd /mnt/SSD2/recognizer_resources_dir/
2021-12-04 20:26:04: Loading relational tables
2021-12-04 20:26:08: Replacing spaces for commas
2021-12-04 20:26:08: Running annotation with RPS-BLAST and CDD database as reference.
/mnt/SSD2/recognizer_resources_dir/dbs/cd.aux not found! Rebuilding database...
Some part of cd was not valid! Will rebuild!
Traceback (most recent call last):
  File "/home/jang/anaconda3/envs/deepnog/bin/recognizer.py", line 892, in <module>
    main()
  File "/home/jang/anaconda3/envs/deepnog/bin/recognizer.py", line 883, in main
    max_target_seqs=args.max_target_seqs, evalue=args.evalue)
  File "/home/jang/anaconda3/envs/deepnog/bin/recognizer.py", line 794, in multiprocess_workflow
    db_report = pd.DataFrame(columns=['qseqid', 'sseqid', 'SUPERFAMILIES', 'SITES', 'MOTIFS'])
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'

Any hints?

Bests,
Jan

**Comment by gaworj** [comment]
I did one more thing to be sure.
Created new conda env for recognizer and installed the tool in it.
Problem still persist:

tar -xzf cdd.tar.gz --wildcards "*.smp"
unxz: taxonomy.rdf: File exists
Reading RDF taxonomy
Converting XML taxonomy.rdf to TSV format: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2711822/2711822 [00:06<00:00, 441364.16it/s]
2021-12-04 20:58:19: Loading relational tables
Organizing COGs corresponding to each tax ID: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4866/4866 [00:33<00:00, 144.25it/s]
2021-12-04 20:59:00: Replacing spaces for commas
2021-12-04 20:59:00: Running annotation with RPS-BLAST and CDD database as reference.
/mnt/SSD2/recognizer_resources_dir/dbs/cd.aux not found! Rebuilding database...
Some part of cd was not valid! Will rebuild!
Traceback (most recent call last):
  File "/home/jang/anaconda3/envs/recognizer/bin/recognizer.py", line 892, in <module>
    main()
  File "/home/jang/anaconda3/envs/recognizer/bin/recognizer.py", line 883, in main
    max_target_seqs=args.max_target_seqs, evalue=args.evalue)
  File "/home/jang/anaconda3/envs/recognizer/bin/recognizer.py", line 794, in multiprocess_workflow
    db_report = pd.DataFrame(columns=['qseqid', 'sseqid', 'SUPERFAMILIES', 'SITES', 'MOTIFS'])
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'

**Comment by iquasere** [comment]
Can you check your version of reCOGnizer? What is the output of ```recognizer.py -v```?

If you don't have the last version (```1.6.3```), I advise installing it and checking if the problem persists. Otherwise, I ask you to send me the input file, so I can test on my end.

**Comment by gaworj** [comment]
Thank you for fast reply.

Here is the version check result:

recognizer.py -v
reCOGnizer [1.6.3]

I cannot provide my current genome sequence but I have also tried on the previous genome which previously worked:
https://www.ncbi.nlm.nih.gov/nuccore/NZ_CP009273.1

Downloaded protein fasta file from GenBank and tried to run:

recognizer.py -t 12 -f BW25113_NCBI_protein_sequence.txt -o BW25113_NCBI_protein_recognizer_COG_out -rd /mnt/SSD2/recognizer_resources_dir


Created BW25113_NCBI_protein_recognizer_COG_out/fasta
Created BW25113_NCBI_protein_recognizer_COG_out/asn
Created BW25113_NCBI_protein_recognizer_COG_out/blast
Created BW25113_NCBI_protein_recognizer_COG_out/rpsbproc
Created BW25113_NCBI_protein_recognizer_COG_out/tmp
2021-12-06 13:21:16: Loading relational tables
2021-12-06 13:21:20: Replacing spaces for commas
2021-12-06 13:21:20: Running annotation with RPS-BLAST and CDD database as reference.
/mnt/SSD2/recognizer_resources_dir/dbs/cd.pdb not found! Rebuilding database...
Some part of cd was not valid! Will rebuild!
Deleted existing BLAST database with identical name.
Traceback (most recent call last):
  File "/home/jang/anaconda3/envs/recognizer/bin/recognizer.py", line 892, in <module>
    main()
  File "/home/jang/anaconda3/envs/recognizer/bin/recognizer.py", line 883, in main
    max_target_seqs=args.max_target_seqs, evalue=args.evalue)
  File "/home/jang/anaconda3/envs/recognizer/bin/recognizer.py", line 794, in multiprocess_workflow
    db_report = pd.DataFrame(columns=['qseqid', 'sseqid', 'SUPERFAMILIES', 'SITES', 'MOTIFS'])
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/home/jang/anaconda3/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1440, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'

**Comment by iquasere** [comment]
Could you provide the file (or link) of the annotated genome? I'm not finding it there

**Comment by gaworj** [comment]
I will send you via e-mail.

**Comment by gaworj** [comment]
Dear Joao,   Please find attached protein fasta file for my E.coli strain.  Interestingly it was working with the previous version of the recognizer.   Bests,  Jan  Jan Gawor M.Sc.  Customer Service   DNA Sequencing and Oligonucleotide Synthesis Laboratory IBB PAS  ***@***.***  www.oligo.pl www.oligo.pl    tel. (+48) 22 592 34 02  fax  (+48) 22 668 71 09   www.researchgate.net https://www.researchgate.net/profile/Jan_Gawor  www.scopus.com https://www.scopus.com/authid/detail.uri?authorId=49961128100    
            
          
     
      
       
        Dnia 7 grudnia 2021 13:41 João Sequeira ***@***.***&gt; napisał(a):
       
    
       
         
 Could you provide the file (or link) of the annotated genome? I&#39;m not finding it there

**Comment by iquasere** [comment]
Hi, Jan!

The email you sent contains no annexed files on my end! Please do send it
again with them attached, as I am very interested in solving this problem!
Also, do send the command you are using to run reCOGnizer, so I can test it
on my end. The problem here is that reCOGnizer is passing my local tests,
but something may be escaping them!

Alternatively, you may want to use the previous version of reCOGnizer that
was working! You can install it with conda install -c conda-forge -c
bioconda recognizer=version_you_want (e.g. 1.2.3). You can see the list of
versions here <https://github.com/iquasere/reCOGnizer/releases>, and check
what was the version that worked by the respective dates of release.

Thank you for your help!

Jan Gawor ***@***.***> escreveu no dia sábado, 11/12/2021
à(s) 20:50:

**Comment by iquasere** [comment]
As communicated through email, I ran reCOGnizer 1.6.3 on this FASTA file, and it worked fine.

My suggestion is to remove the ```resources_directory``` folder, since in its latter versions, reCOGnizer’s handling of this folder suffered significant alterations. After that, reinstall reCOGnizer, and run it with the ```--download-resources``` flag again. 
 
I will close the issue for now, but do reopen it if the problem persists!
